config/routes.rb
Rails.application.routes.draw do
  get 'resumes/index'
  get 'resumes/new'
  get 'resumes/create'
  get 'resumes/destroy'
  devise_for :users
	root "pages#index"
	resources :posts do
		resources :comments
		end

	get '/about', to: 'pages#about'
  	resources :contact, only: [:index, :new, :create]
	resources :resumes, only: [:index, :new, :create, :destroy]

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,	:validate => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "User Message from your profile page",
      :to => "121015070@sastra.ac.in",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
	validates :body,  presence: true
end

app/models/resume.rb
class Resume < ApplicationRecord
mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   validates :name, presence: true # Make sure the owner's name is present.
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def index
    @contact = Contact.new(params[:contact])
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request

      if @contact.deliver
        # re-initialize Contact object for cleared form
       flash[:success] = "Message sent successfully."
	    redirect_to	root_path
	
      else
		flash[:error] =  "Cannot send message"
		redirect_to	root_path
       
	   
	   
      end

    
  end
  
end

  

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def about
	end
	
	def index
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order('created_at DESC')
	end
	def new
		 unless current_user.admin?
			flash[:danger] = "You are not allowed to access this page."
			redirect_to posts_path
		 end
		@post = Post.new
	end
	
	def show
		@post = Post.find(params[:id])
	end
	
	def create
		@post = Post.new(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
		
	end
	
	def edit
		@post = Post.find(params[:id])
	end
	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end
	
	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end
	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
      @resumes = Resume.all
   end
   
   def new
      @resume = Resume.new
   end
   
   def create
      @resume = Resume.new(resume_params)
      
      if @resume.save
         redirect_to resumes_path, notice: "The resume #{@resume.name} has been uploaded."
      else
         render "new"
      end
      
   end
   
   def destroy
      @resume = Resume.find(params[:id])
      @resume.destroy
      redirect_to resumes_path, notice:  "The resume #{@resume.name} has been deleted."
   end
   
   private
      def resume_params
      params.require(:resume).permit(:name, :attachment)
   end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>

	
 	<p><%= link_to 'Delete', [comment.post, comment],
								  method: :delete,
								  class: "button",
								 	data: { confirm: 'Are you sure?' } %></p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<%= f.label :name %><br>
	<%= f.text_field :name %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_area :body %><br>
	<br>
	<%= f.submit %>
<% end %>

app/views/contact/_contact_form.html.erb
<div id="page_wrapper">
<%= form_for @contact, url: contact_index_path, remote: true do |f| %>
	<p>
	  <%= flash[:success] unless flash[:success].blank? %>
	  <%= flash[:error] unless flash[:error].blank? %>
	</p>
    <div class="col-md-6">
        <%= f.label :name %></br>
        <%= f.text_field  :name, required: true, class: "contact-form-text-area" %></br>

        <%= f.label :email %></br>
        <%= f.text_field :email, required: true, class: "contact-form-text-area" %></br>

      <%= f.label :message %></br>
      <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-text-area",
                        placeholder: "Send me a message"%></br>


      <%= f.submit 'Send Message', class: 'btn btn-primary' %>
	  
    </div>
  <% end %>
  
  
  
</div>

app/views/contact/index.html.erb
<h3 align="center">Message me by passing your Name, Email. I will get back.</h3>
	<p>
	  <%= flash[:success] unless flash[:success].blank? %>
	  <%= flash[:error] unless flash[:error].blank? %>
	</p>
  <div id="contact">
  
    <%= render 'contact_form' %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyProfile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
	  <div id="sidebar">

			<ul>
				
				<li><%= link_to "About Me", about_path %></li>
				<li><%= link_to "Blog", posts_path %></li>
				<li><%= link_to "Contact Me", contact_index_path %></li>
				<li><%= link_to "My Resume", resumes_index_path %></li>
				
				
			</ul>

			<ul>
				<li class="category">Social</li>
				
				<li><a href="https://mobile.twitter.com/PaluruSravika">Twitter</a></li>
				<li><a href="https://github.com/Sravika2509?tab=repositories">Github</a></li>
				<li><a href="mailto:121015070@sastra.ac.in">Email</a></li>
			</ul>
		</div>
		
		<div id="main_content">
		<div id="header">
			<% if current_page?(root_path) %>
				<p>My Profile</p>
			<% elsif current_page?(about_path) %>
				<p>About My self</p>
				<div class="buttons">
					<button class="button"><%= link_to "Back Main Page", root_path %></button>
				</div>	
			<% elsif current_page?(posts_path) %>
				<p>All Posts</p>
				<% if user_signed_in? %>
				<p align="center">Logged in as <strong><%= current_user.email %></strong>
					<div class="buttons">
					<% if current_user.admin? %>
						<button class="button"><%= link_to "New Post", new_post_path %></button>
					<% end %>
						<button class="button"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></button>
					</div>
					
					<% else %>
					
				<button class="button" style="float: right;"><%= link_to "Log In", new_user_session_path %></button>
				<button class="button" style="float: right;"><%= link_to "Sign Up", new_user_registration_path %></button>
			
			
				<% end %>
			<% elsif current_page?(contact_index_path) %>
				<p>Contact Me Page</p>
				
			<div class="buttons">
			<button class="button"><%= link_to "Back Main Page", root_path %></button>
			</div>	
				
			<% else %>
				<%= link_to "Back Main Page", posts_path %>
			<% end %>
			
			
		</div>

		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>

		<%= yield %>
	</div>
		
    
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "logo.png" , height: '300', width: '200' %>
	</div>

	<div id="content">
		<h2>Hey, I'm Sravika</h2>
		<p>Welcome to my Profile page.</p>
		<p>This is Sravika Paluru. I am currently pursuing graduation degree( Information Technology ) from Sastra Deemed University. </p>
		<p>I am from Thatiparthi in Nellore district, Andhra Pradesh</p><br><br><br>
		<p class="header"><strong>Hobbies</strong></p>
		<p>Reading Books and Listening Music</p>
		<p class="header"><strong>Education</strong></p>
<p>Sastra Deemed University<br />
<strong>Pursuing Information Technology, </strong>4 semesters completed</p>
<p>Intermediate<br />
<strong>Completed Intermediate from Andhra Intermediate board, </strong>got 98.9%</p>
		
	</div>
</div>

app/views/pages/index.html.erb
<div class="jumbotron">
  <h1 class="display-2">Welcome to Sravika Profile</h1>
  <p class="lead" style="color:Orange">This page gives details about me and introduces about me to the world</p>
  <hr class="my-4">
  <p  style="color:green"><b>You can see and know more about me. This website has my blog and also i have given a contact form to reach out to me with a message and that message will be received in my inbox. Please provide your name and email so that i can reach you.</b> </p>
  <p style="color:green">Feel free to read my blog and provide comments. You can find my resume also in this space.</p>
  
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_field :body %><br>
	<br>
	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title"><%= link_to post.title, post %></h2>
		<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
	</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>New Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title"><%= @post.title %></h1>
	<p class="date">
		Submitted <%= time_ago_in_words(@post.created_at) %> Ago

	</p>
	<p class="body"><%= @post.body %></p>
	<% if current_user.admin? %>
		<button class="button"><%= link_to 'Edit', edit_post_path(@post) %> </button>
		<button class="button"><%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %></button>
	<% end %>
	<div id="comments">
		<h2><%= @post.comments.count %> Comments</h2>
		<%= render @post.comments %>

		<h3>Add a comment:</h3>
		<%= render "comments/form" %>
	</div>
</div>

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<button class="button"><%= link_to "New Resume", new_resume_path, class: "btn btn-primary" %></button>
<br />
<br />

<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<table class = "table table-bordered table-striped">
   <thead>.
      <tr>
         <th>Name</th><br>
         <th>Download Link</th>
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% @resumes.each do |resume| %>
         
         <tr>
            <td><%= resume.name %></td>
            <td><u><%= link_to "Download Resume", resume.attachment_url %></u></td>
            <td><%= button_to "Delete",  resume, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
         </tr>
         
      <% end %>
   </tbody>
   
</table>

app/views/resumes/new.html.erb
<% if !@resume.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @resume.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

<div class = "well">
   <%= form_for @resume, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>